### ISSUE TITLE
[BUG]  Anki > Preferences on macOS shows the Migaku Settings instead of Anki settings

### ISSUE THREAD

**Issue by alyssabedard** [migaku-official/Migaku-Anki-Extension#11]
Hello, 
Under Anki > Preferences on macOS it shows the Migaku settings instead of Anki settings.
The Migaku settings don't show in the toolbar.

Anki: 2.1.49 (most recent)
OS: macOS Monterey 12.1
Migaku-Anki-Extension : 0.1.0-alpha.6 (most recent)

https://user-images.githubusercontent.com/70352767/147359565-8c0229b6-82aa-4f3a-98eb-5afa23fc7f40.mov

**Comment by RicBent** [comment]
Fixed with https://github.com/migaku-official/Migaku-Anki-Extension/commit/a8f67d4a67a4b00b5f291879efe90b9db6e1aafe

Thanks for the report!
