### ISSUE TITLE
[BUG] Add-on error pop-up window when starting Anki on MacOS

### ISSUE THREAD

**Issue by alyssabedard** [migaku-official/Migaku-Anki-Extension#18]
Hello,

I get the following error window with Migaku-Anki-Extension  **0.1.0-alpha.6** and **0.1.0-alpha.12** on my Mac Mini 2018 and MacBook Air 2020 every time I start Anki:

"Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-01-07 10:19:42

WARNING:pynput.keyboard.Listener:This process is not trusted! Input event monitoring will not be possible until it is added to accessibility clients."

Anki: 2.1.49 
OS: macOS Monterey 12.1
Migaku-Anki-Extension : 0.1.0-alpha.12 and  0.1.0-alpha.6

https://user-images.githubusercontent.com/70352767/148573125-4634e6c9-02e3-468c-bc5d-33705d301407.mov

**Comment by RicBent** [comment]
You need to grant Anki access to accessibility features from the settings. Usually macOS asks you if you want to grant that permission the first time you start Anki with the extension installed. Did you happen to just click that away?

https://user-images.githubusercontent.com/12817990/148596841-4e592cff-b3fa-49b6-a45b-5d0cebe911b3.mp4

**Comment by alyssabedard** [comment]
I didn't get any permission request from MacOS. Now that you mentioned it, I should've checked the Systems Preferences first. 

May I ask which  Migaku-Anki-Extension feature needs accessibility? Is it for the hotkeys? The Migaku add-on works wonderfully on my end without the accessibility access, and I would prefer not to grant full access to Anki. I don't know the add-on needs for accessibility, but maybe it would be interesting in the future to have the option to deny access in the Migaku Settings?  Anyways this is not a priority but thank you for your reply :)

**Comment by RicBent** [comment]
I logged this feature request here: #19

**Comment by mainrs** [comment]
I get the same error __with__ accessability enabled: 

```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Migaku Anki Add-on⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "/Users/me/Library/Application Support/Anki2/addons21/1846879528/__init__.py", line 38, in <module>
    from . import (
  File "/Users/me/Library/Application Support/Anki2/addons21/1846879528/welcome_wizard.py", line 9, in <module>
    from .global_hotkeys import HotkeyConfigWidget, hotkey_handler
  File "/Users/me/Library/Application Support/Anki2/addons21/1846879528/global_hotkeys.py", line 4, in <module>
    import pynput.keyboard
  File "/Users/me/Library/Application Support/Anki2/addons21/1846879528/lib/shared/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/Users/me/Library/Application Support/Anki2/addons21/1846879528/lib/shared/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/Users/me/Library/Application Support/Anki2/addons21/1846879528/lib/shared/pynput/_util/__init__.py", line 77, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: cannot import name '_objc' from partially initialized module 'objc' (most likely due to a circular import) (/Users/me/Library/Application Support/Anki2/addons21/1846879528/lib/macos/objc/__init__.py)

Try one of the following resolutions:

 * Please make sure that you have Python bindings for the system frameworks installed

```

<img width="657" alt="image" src="https://user-images.githubusercontent.com/5113257/169147852-9d16955b-7292-434e-a785-58284c4790ee.png">

Version ⁨2.1.52 (ab1c2395)⁩
Python 3.9.7 Qt 6.3.0 PyQt 6.3.0
Addon: Newest that Anki installs when pressing check update.

**Comment by RicBent** [comment]
Hmm, this is actually unrelated to the issues before.

What exact macOS version are you on and what exact system are you on?

**Comment by rameauv** [comment]
Got the exact same bug after upgrading anki, seems to be happening on every versions superior to 2.49.
Apparently they switched to python 3.9 in anki 2.50 https://github.com/ankitects/anki/releases/tag/2.1.50. 
Might be linked.

**Comment by mainrs** [comment]
> Hmm, this is actually unrelated to the issues before.
> 
> What exact macOS version are you on and what exact system are you on?

The macOS version is in the comment. macOS 11.6.1.
